export const intialDevelopers = [
    {
        id: '1',
        name: 'John Doe',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com',
        github: 'https://github.com',
        website: 'https://website.com',
        email: '', 
        phone: '',
        skill: ['Python', 'Django', 'AWS'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '2',
        name: 'Jane Doe',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com',
        github: 'https://github.com',
        website: 'https://website.com',
        email: '', 
        phone: '',
        skills: ['Python', 'Django', 'AWS'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '3',
        name: 'John Smith',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com',
        github: 'https://github.com',
        website: 'https://website.com',
        email: '', 
        phone: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '4',
        name: 'Jane Smith',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com',
        github: 'https://github.com',
        website: 'https://website.com',
        email: '',
        phone: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '5',
        name: 'John Doe',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com', 
        github: 'https://github.com',
        website: 'https://website.com',
        email: '',
        phone: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: '6',
        name: 'John Moe',
        avatar: 'https://avatars.dicebear.com/api',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel libero sit amet nunc.',
        followers: 100,
        following: 100,
        repos: 100,
        stars: 100,
        forks: 100,
        issues: 100,
        pullRequests: 100,
        projects: 100,
        packages: 100,
        organizations: 100,
        location: 'San Francisco, CA',
        twitter: 'https://twitter.com', 
        github: 'https://github.com',
        website: 'https://website.com',
        email: '',
        phone: '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
]